# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RPGH_main_gui_signals_sorted.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 584)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mpl_tab = QtWidgets.QWidget()
        self.mpl_tab.setObjectName("mpl_tab")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout(self.mpl_tab)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.mpl_tab)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.mpl = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.tabWidget_4.addTab(self.mpl, "")
        self.mpl1 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl1.sizePolicy().hasHeightForWidth())
        self.mpl1.setSizePolicy(sizePolicy)
        self.mpl1.setObjectName("mpl1")
        self.tabWidget_4.addTab(self.mpl1, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.tab_16)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.groupBox_31 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_31.setTitle("")
        self.groupBox_31.setObjectName("groupBox_31")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout(self.groupBox_31)
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.label_75 = QtWidgets.QLabel(self.groupBox_31)
        self.label_75.setObjectName("label_75")
        self.gridLayout_32.addWidget(self.label_75, 0, 0, 1, 1)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.horizontalLayout_59.addWidget(self.lcdNumber_3)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_59.addWidget(self.lcdNumber_2)
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_59.addWidget(self.lcdNumber)
        self.gridLayout_32.addLayout(self.horizontalLayout_59, 3, 1, 1, 1)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.lcdNumber_37 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_37.setObjectName("lcdNumber_37")
        self.horizontalLayout_56.addWidget(self.lcdNumber_37)
        self.lcdNumber_38 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_38.setObjectName("lcdNumber_38")
        self.horizontalLayout_56.addWidget(self.lcdNumber_38)
        self.gridLayout_32.addLayout(self.horizontalLayout_56, 0, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.groupBox_31)
        self.label_78.setObjectName("label_78")
        self.gridLayout_32.addWidget(self.label_78, 2, 0, 1, 1)
        self.lcdNumber_32 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_32.setObjectName("lcdNumber_32")
        self.gridLayout_32.addWidget(self.lcdNumber_32, 1, 1, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.groupBox_31)
        self.label_85.setObjectName("label_85")
        self.gridLayout_32.addWidget(self.label_85, 4, 0, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.groupBox_31)
        self.label_77.setObjectName("label_77")
        self.gridLayout_32.addWidget(self.label_77, 5, 0, 1, 1)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.lcdNumber_39 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_39.setObjectName("lcdNumber_39")
        self.horizontalLayout_58.addWidget(self.lcdNumber_39)
        self.gridLayout_32.addLayout(self.horizontalLayout_58, 5, 1, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.groupBox_31)
        self.label_74.setObjectName("label_74")
        self.gridLayout_32.addWidget(self.label_74, 1, 0, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.groupBox_31)
        self.label_76.setObjectName("label_76")
        self.gridLayout_32.addWidget(self.label_76, 3, 0, 1, 1)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.lcdNumber_35 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_35.setObjectName("lcdNumber_35")
        self.horizontalLayout_55.addWidget(self.lcdNumber_35)
        self.lcdNumber_36 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_36.setObjectName("lcdNumber_36")
        self.horizontalLayout_55.addWidget(self.lcdNumber_36)
        self.gridLayout_32.addLayout(self.horizontalLayout_55, 2, 1, 1, 1)
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.lcdNumber_33 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_33.setObjectName("lcdNumber_33")
        self.horizontalLayout_64.addWidget(self.lcdNumber_33)
        self.lcdNumber_40 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_40.setObjectName("lcdNumber_40")
        self.horizontalLayout_64.addWidget(self.lcdNumber_40)
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.groupBox_31)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.horizontalLayout_64.addWidget(self.lcdNumber_7)
        self.gridLayout_32.addLayout(self.horizontalLayout_64, 4, 1, 1, 1)
        self.horizontalLayout_54.addLayout(self.gridLayout_32)
        self.horizontalLayout_57.addWidget(self.groupBox_31)
        self.tabWidget_4.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout(self.tab_17)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.groupBox_30 = QtWidgets.QGroupBox(self.tab_17)
        self.groupBox_30.setTitle("")
        self.groupBox_30.setObjectName("groupBox_30")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.groupBox_30)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_69 = QtWidgets.QLabel(self.groupBox_30)
        self.label_69.setObjectName("label_69")
        self.gridLayout_31.addWidget(self.label_69, 1, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.groupBox_30)
        self.label_70.setObjectName("label_70")
        self.gridLayout_31.addWidget(self.label_70, 0, 0, 1, 1)
        self.lcdNumber_25 = QtWidgets.QLCDNumber(self.groupBox_30)
        self.lcdNumber_25.setObjectName("lcdNumber_25")
        self.gridLayout_31.addWidget(self.lcdNumber_25, 1, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.groupBox_30)
        self.label_71.setObjectName("label_71")
        self.gridLayout_31.addWidget(self.label_71, 3, 0, 1, 1)
        self.lcdNumber_26 = QtWidgets.QLCDNumber(self.groupBox_30)
        self.lcdNumber_26.setObjectName("lcdNumber_26")
        self.gridLayout_31.addWidget(self.lcdNumber_26, 4, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox_30)
        self.label_72.setObjectName("label_72")
        self.gridLayout_31.addWidget(self.label_72, 4, 0, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.groupBox_30)
        self.label_73.setObjectName("label_73")
        self.gridLayout_31.addWidget(self.label_73, 2, 0, 1, 1)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.lcdNumber_28 = QtWidgets.QLCDNumber(self.groupBox_30)
        self.lcdNumber_28.setObjectName("lcdNumber_28")
        self.horizontalLayout_51.addWidget(self.lcdNumber_28)
        self.lcdNumber_29 = QtWidgets.QLCDNumber(self.groupBox_30)
        self.lcdNumber_29.setObjectName("lcdNumber_29")
        self.horizontalLayout_51.addWidget(self.lcdNumber_29)
        self.gridLayout_31.addLayout(self.horizontalLayout_51, 2, 1, 1, 1)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.lcdNumber_30 = QtWidgets.QLCDNumber(self.groupBox_30)
        self.lcdNumber_30.setObjectName("lcdNumber_30")
        self.horizontalLayout_52.addWidget(self.lcdNumber_30)
        self.lcdNumber_31 = QtWidgets.QLCDNumber(self.groupBox_30)
        self.lcdNumber_31.setObjectName("lcdNumber_31")
        self.horizontalLayout_52.addWidget(self.lcdNumber_31)
        self.gridLayout_31.addLayout(self.horizontalLayout_52, 0, 1, 1, 1)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.groupBox_30)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.horizontalLayout_60.addWidget(self.lcdNumber_6)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.groupBox_30)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.horizontalLayout_60.addWidget(self.lcdNumber_5)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox_30)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.horizontalLayout_60.addWidget(self.lcdNumber_4)
        self.gridLayout_31.addLayout(self.horizontalLayout_60, 3, 1, 1, 1)
        self.horizontalLayout_50.addLayout(self.gridLayout_31)
        self.horizontalLayout_53.addWidget(self.groupBox_30)
        self.tabWidget_4.addTab(self.tab_17, "")
        self.horizontalLayout_48.addWidget(self.tabWidget_4)
        self.horizontalLayout_49.addLayout(self.horizontalLayout_48)
        self.tabWidget.addTab(self.mpl_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_38 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_38.setEnabled(False)
        self.groupBox_38.setObjectName("groupBox_38")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout(self.groupBox_38)
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.gridLayout_37 = QtWidgets.QGridLayout()
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.light_control_onoff = QtWidgets.QRadioButton(self.groupBox_38)
        self.light_control_onoff.setChecked(True)
        self.light_control_onoff.setObjectName("light_control_onoff")
        self.gridLayout_37.addWidget(self.light_control_onoff, 0, 0, 1, 1)
        self.light_control_pid = QtWidgets.QRadioButton(self.groupBox_38)
        self.light_control_pid.setObjectName("light_control_pid")
        self.gridLayout_37.addWidget(self.light_control_pid, 1, 0, 1, 1)
        self.horizontalLayout_67.addLayout(self.gridLayout_37)
        self.gridLayout.addWidget(self.groupBox_38, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 3, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 2, 1, 1)
        self.light_light_max = QtWidgets.QSpinBox(self.groupBox_4)
        self.light_light_max.setMaximum(10000)
        self.light_light_max.setObjectName("light_light_max")
        self.gridLayout_4.addWidget(self.light_light_max, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.light_light_min = QtWidgets.QSpinBox(self.groupBox_4)
        self.light_light_min.setMaximum(10000)
        self.light_light_min.setObjectName("light_light_min")
        self.gridLayout_4.addWidget(self.light_light_min, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_4)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.light_rgb_red = QtWidgets.QSpinBox(self.groupBox_2)
        self.light_rgb_red.setEnabled(False)
        self.light_rgb_red.setMaximum(255)
        self.light_rgb_red.setProperty("value", 255)
        self.light_rgb_red.setObjectName("light_rgb_red")
        self.gridLayout_6.addWidget(self.light_rgb_red, 0, 0, 1, 1)
        self.light_rgb_green = QtWidgets.QSpinBox(self.groupBox_2)
        self.light_rgb_green.setEnabled(False)
        self.light_rgb_green.setMaximum(255)
        self.light_rgb_green.setProperty("value", 255)
        self.light_rgb_green.setObjectName("light_rgb_green")
        self.gridLayout_6.addWidget(self.light_rgb_green, 1, 0, 1, 1)
        self.light_rgb_blue = QtWidgets.QSpinBox(self.groupBox_2)
        self.light_rgb_blue.setEnabled(False)
        self.light_rgb_blue.setMaximum(255)
        self.light_rgb_blue.setProperty("value", 255)
        self.light_rgb_blue.setObjectName("light_rgb_blue")
        self.gridLayout_6.addWidget(self.light_rgb_blue, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_6)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.light_bool_alert = QtWidgets.QCheckBox(self.groupBox)
        self.light_bool_alert.setObjectName("light_bool_alert")
        self.gridLayout_7.addWidget(self.light_bool_alert, 0, 0, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_7)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.light_trigers_sensors = QtWidgets.QRadioButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.light_trigers_sensors.sizePolicy().hasHeightForWidth())
        self.light_trigers_sensors.setSizePolicy(sizePolicy)
        self.light_trigers_sensors.setObjectName("light_trigers_sensors")
        self.verticalLayout_3.addWidget(self.light_trigers_sensors)
        self.light_trigers_time = QtWidgets.QRadioButton(self.groupBox_5)
        self.light_trigers_time.setObjectName("light_trigers_time")
        self.verticalLayout_3.addWidget(self.light_trigers_time)
        self.light_trigers_off = QtWidgets.QRadioButton(self.groupBox_5)
        self.light_trigers_off.setChecked(True)
        self.light_trigers_off.setObjectName("light_trigers_off")
        self.verticalLayout_3.addWidget(self.light_trigers_off)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_21.sizePolicy().hasHeightForWidth())
        self.groupBox_21.setSizePolicy(sizePolicy)
        self.groupBox_21.setObjectName("groupBox_21")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.groupBox_21)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_31 = QtWidgets.QLabel(self.groupBox_21)
        self.label_31.setObjectName("label_31")
        self.gridLayout_23.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_21)
        self.label_30.setObjectName("label_30")
        self.gridLayout_23.addWidget(self.label_30, 0, 0, 1, 1)
        self.light_sensor_lcd_broadband = QtWidgets.QLCDNumber(self.groupBox_21)
        self.light_sensor_lcd_broadband.setObjectName("light_sensor_lcd_broadband")
        self.gridLayout_23.addWidget(self.light_sensor_lcd_broadband, 1, 1, 1, 1)
        self.light_sensor_lcd_visible = QtWidgets.QLCDNumber(self.groupBox_21)
        self.light_sensor_lcd_visible.setObjectName("light_sensor_lcd_visible")
        self.gridLayout_23.addWidget(self.light_sensor_lcd_visible, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_21)
        self.label_35.setObjectName("label_35")
        self.gridLayout_23.addWidget(self.label_35, 2, 0, 1, 1)
        self.light_sensor_lcd_infrared = QtWidgets.QLCDNumber(self.groupBox_21)
        self.light_sensor_lcd_infrared.setObjectName("light_sensor_lcd_infrared")
        self.gridLayout_23.addWidget(self.light_sensor_lcd_infrared, 2, 1, 1, 1)
        self.horizontalLayout_30.addLayout(self.gridLayout_23)
        self.gridLayout_2.addWidget(self.groupBox_21, 0, 4, 1, 1)
        self.groupBox_35 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_35.setEnabled(False)
        self.groupBox_35.setObjectName("groupBox_35")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout(self.groupBox_35)
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_35)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_34.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.groupBox_35)
        self.label_80.setObjectName("label_80")
        self.gridLayout_34.addWidget(self.label_80, 1, 0, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.groupBox_35)
        self.label_79.setObjectName("label_79")
        self.gridLayout_34.addWidget(self.label_79, 0, 0, 1, 1)
        self.light_pid_control_kp = QtWidgets.QDoubleSpinBox(self.groupBox_35)
        self.light_pid_control_kp.setMaximum(5.0)
        self.light_pid_control_kp.setSingleStep(0.05)
        self.light_pid_control_kp.setProperty("value", 1.0)
        self.light_pid_control_kp.setObjectName("light_pid_control_kp")
        self.gridLayout_34.addWidget(self.light_pid_control_kp, 0, 1, 1, 1)
        self.light_pid_control_kd = QtWidgets.QDoubleSpinBox(self.groupBox_35)
        self.light_pid_control_kd.setObjectName("light_pid_control_kd")
        self.gridLayout_34.addWidget(self.light_pid_control_kd, 2, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.groupBox_35)
        self.label_81.setObjectName("label_81")
        self.gridLayout_34.addWidget(self.label_81, 2, 0, 1, 1)
        self.horizontalLayout_63.addLayout(self.gridLayout_34)
        self.gridLayout_2.addWidget(self.groupBox_35, 2, 4, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.light_time_on = QtWidgets.QTimeEdit(self.groupBox_3)
        self.light_time_on.setEnabled(False)
        self.light_time_on.setObjectName("light_time_on")
        self.gridLayout_5.addWidget(self.light_time_on, 0, 1, 1, 1)
        self.light_time_off = QtWidgets.QTimeEdit(self.groupBox_3)
        self.light_time_off.setEnabled(False)
        self.light_time_off.setObjectName("light_time_off")
        self.gridLayout_5.addWidget(self.light_time_off, 1, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_5)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.temperature_trigers_sensors = QtWidgets.QRadioButton(self.groupBox_8)
        self.temperature_trigers_sensors.setObjectName("temperature_trigers_sensors")
        self.verticalLayout_4.addWidget(self.temperature_trigers_sensors)
        self.temperature_trigers_time = QtWidgets.QRadioButton(self.groupBox_8)
        self.temperature_trigers_time.setObjectName("temperature_trigers_time")
        self.verticalLayout_4.addWidget(self.temperature_trigers_time)
        self.temperature_trigers_off = QtWidgets.QRadioButton(self.groupBox_8)
        self.temperature_trigers_off.setChecked(True)
        self.temperature_trigers_off.setObjectName("temperature_trigers_off")
        self.verticalLayout_4.addWidget(self.temperature_trigers_off)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout_8.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 0, 0, 1, 1)
        self.temperature_temp_max = QtWidgets.QSpinBox(self.groupBox_7)
        self.temperature_temp_max.setObjectName("temperature_temp_max")
        self.gridLayout_9.addWidget(self.temperature_temp_max, 0, 1, 1, 1)
        self.temperature_temp_min = QtWidgets.QSpinBox(self.groupBox_7)
        self.temperature_temp_min.setObjectName("temperature_temp_min")
        self.gridLayout_9.addWidget(self.temperature_temp_min, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 1, 2, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_9)
        self.gridLayout_8.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setEnabled(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_14 = QtWidgets.QLabel(self.groupBox_9)
        self.label_14.setEnabled(False)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_9)
        self.label_15.setEnabled(False)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 1, 0, 1, 1)
        self.temperature_time_heating_on = QtWidgets.QTimeEdit(self.groupBox_9)
        self.temperature_time_heating_on.setEnabled(False)
        self.temperature_time_heating_on.setObjectName("temperature_time_heating_on")
        self.gridLayout_10.addWidget(self.temperature_time_heating_on, 0, 1, 1, 1)
        self.temperature_time_heating_off = QtWidgets.QTimeEdit(self.groupBox_9)
        self.temperature_time_heating_off.setEnabled(False)
        self.temperature_time_heating_off.setObjectName("temperature_time_heating_off")
        self.gridLayout_10.addWidget(self.temperature_time_heating_off, 1, 1, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_10)
        self.gridLayout_8.addWidget(self.groupBox_9, 3, 1, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.temperature_bool_temp_alert = QtWidgets.QCheckBox(self.groupBox_10)
        self.temperature_bool_temp_alert.setObjectName("temperature_bool_temp_alert")
        self.verticalLayout_7.addWidget(self.temperature_bool_temp_alert)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        self.gridLayout_8.addWidget(self.groupBox_10, 3, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setEnabled(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_58 = QtWidgets.QLabel(self.groupBox_6)
        self.label_58.setObjectName("label_58")
        self.gridLayout_3.addWidget(self.label_58, 1, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox_6)
        self.label_57.setObjectName("label_57")
        self.gridLayout_3.addWidget(self.label_57, 0, 0, 1, 1)
        self.temperature_time_venting_on = QtWidgets.QTimeEdit(self.groupBox_6)
        self.temperature_time_venting_on.setObjectName("temperature_time_venting_on")
        self.gridLayout_3.addWidget(self.temperature_time_venting_on, 0, 1, 1, 1)
        self.temperature_time_venting_off = QtWidgets.QTimeEdit(self.groupBox_6)
        self.temperature_time_venting_off.setObjectName("temperature_time_venting_off")
        self.gridLayout_3.addWidget(self.temperature_time_venting_off, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout_8.addWidget(self.groupBox_6, 0, 2, 1, 1)
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_25.setObjectName("groupBox_25")
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout(self.groupBox_25)
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.label_44 = QtWidgets.QLabel(self.groupBox_25)
        self.label_44.setObjectName("label_44")
        self.gridLayout_35.addWidget(self.label_44, 3, 0, 1, 1)
        self.lcdNumber_13 = QtWidgets.QLCDNumber(self.groupBox_25)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.gridLayout_35.addWidget(self.lcdNumber_13, 1, 1, 1, 1)
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.groupBox_25)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.gridLayout_35.addWidget(self.lcdNumber_8, 0, 1, 1, 1)
        self.lcdNumber_20 = QtWidgets.QLCDNumber(self.groupBox_25)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.gridLayout_35.addWidget(self.lcdNumber_20, 3, 1, 1, 1)
        self.lcdNumber_19 = QtWidgets.QLCDNumber(self.groupBox_25)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.gridLayout_35.addWidget(self.lcdNumber_19, 2, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_25)
        self.label_32.setObjectName("label_32")
        self.gridLayout_35.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_25)
        self.label_43.setObjectName("label_43")
        self.gridLayout_35.addWidget(self.label_43, 2, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_25)
        self.label_33.setObjectName("label_33")
        self.gridLayout_35.addWidget(self.label_33, 1, 0, 1, 1)
        self.horizontalLayout_65.addLayout(self.gridLayout_35)
        self.gridLayout_8.addWidget(self.groupBox_25, 0, 3, 1, 1)
        self.groupBox_34 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_34.setEnabled(False)
        self.groupBox_34.setObjectName("groupBox_34")
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout(self.groupBox_34)
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_34)
        self.doubleSpinBox_5.setEnabled(False)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_13.addWidget(self.doubleSpinBox_5, 1, 1, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox_34)
        self.doubleSpinBox_6.setEnabled(False)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_13.addWidget(self.doubleSpinBox_6, 2, 1, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_34)
        self.doubleSpinBox_4.setEnabled(False)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_13.addWidget(self.doubleSpinBox_4, 0, 1, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.groupBox_34)
        self.label_82.setEnabled(False)
        self.label_82.setObjectName("label_82")
        self.gridLayout_13.addWidget(self.label_82, 0, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.groupBox_34)
        self.label_83.setEnabled(False)
        self.label_83.setObjectName("label_83")
        self.gridLayout_13.addWidget(self.label_83, 1, 0, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.groupBox_34)
        self.label_84.setEnabled(False)
        self.label_84.setObjectName("label_84")
        self.gridLayout_13.addWidget(self.label_84, 2, 0, 1, 1)
        self.horizontalLayout_62.addLayout(self.gridLayout_13)
        self.gridLayout_8.addWidget(self.groupBox_34, 3, 3, 1, 1)
        self.groupBox_36 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_36.setEnabled(False)
        self.groupBox_36.setObjectName("groupBox_36")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.groupBox_36)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.temperature_control_onoff = QtWidgets.QRadioButton(self.groupBox_36)
        self.temperature_control_onoff.setObjectName("temperature_control_onoff")
        self.gridLayout_24.addWidget(self.temperature_control_onoff, 0, 0, 1, 1)
        self.temperature_control_pid = QtWidgets.QRadioButton(self.groupBox_36)
        self.temperature_control_pid.setObjectName("temperature_control_pid")
        self.gridLayout_24.addWidget(self.temperature_control_pid, 1, 0, 1, 1)
        self.horizontalLayout_33.addLayout(self.gridLayout_24)
        self.gridLayout_8.addWidget(self.groupBox_36, 3, 2, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_8)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_18 = QtWidgets.QLabel(self.groupBox_13)
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_13)
        self.label_19.setObjectName("label_19")
        self.gridLayout_12.addWidget(self.label_19, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_13)
        self.label_16.setObjectName("label_16")
        self.gridLayout_12.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_13)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 1, 0, 1, 1)
        self.humidity_humidity_max = QtWidgets.QSpinBox(self.groupBox_13)
        self.humidity_humidity_max.setObjectName("humidity_humidity_max")
        self.gridLayout_12.addWidget(self.humidity_humidity_max, 0, 1, 1, 1)
        self.humidity_humidity_min = QtWidgets.QSpinBox(self.groupBox_13)
        self.humidity_humidity_min.setObjectName("humidity_humidity_min")
        self.gridLayout_12.addWidget(self.humidity_humidity_min, 1, 1, 1, 1)
        self.horizontalLayout_16.addLayout(self.gridLayout_12)
        self.gridLayout_11.addWidget(self.groupBox_13, 0, 1, 1, 1)
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_23.setObjectName("groupBox_23")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.groupBox_23)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.hum_outside_lcdNumber_8 = QtWidgets.QLCDNumber(self.groupBox_23)
        self.hum_outside_lcdNumber_8.setObjectName("hum_outside_lcdNumber_8")
        self.gridLayout_25.addWidget(self.hum_outside_lcdNumber_8, 0, 0, 1, 1)
        self.horizontalLayout_31.addLayout(self.gridLayout_25)
        self.gridLayout_11.addWidget(self.groupBox_23, 0, 2, 1, 1)
        self.groupBox_37 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_37.setObjectName("groupBox_37")
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout(self.groupBox_37)
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.label_88 = QtWidgets.QLabel(self.groupBox_37)
        self.label_88.setObjectName("label_88")
        self.gridLayout_36.addWidget(self.label_88, 0, 0, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.groupBox_37)
        self.label_89.setObjectName("label_89")
        self.gridLayout_36.addWidget(self.label_89, 1, 0, 1, 1)
        self.lcdNumber_14 = QtWidgets.QLCDNumber(self.groupBox_37)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.gridLayout_36.addWidget(self.lcdNumber_14, 0, 1, 1, 1)
        self.lcdNumber_15 = QtWidgets.QLCDNumber(self.groupBox_37)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.gridLayout_36.addWidget(self.lcdNumber_15, 1, 1, 1, 1)
        self.horizontalLayout_66.addLayout(self.gridLayout_36)
        self.gridLayout_11.addWidget(self.groupBox_37, 2, 2, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.humidity_trigers_sensors = QtWidgets.QRadioButton(self.groupBox_11)
        self.humidity_trigers_sensors.setObjectName("humidity_trigers_sensors")
        self.verticalLayout_5.addWidget(self.humidity_trigers_sensors)
        self.humidity_trigers_off = QtWidgets.QRadioButton(self.groupBox_11)
        self.humidity_trigers_off.setChecked(True)
        self.humidity_trigers_off.setObjectName("humidity_trigers_off")
        self.verticalLayout_5.addWidget(self.humidity_trigers_off)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.gridLayout_11.addWidget(self.groupBox_11, 0, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_12.setEnabled(False)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.humidity_bool_vent = QtWidgets.QCheckBox(self.groupBox_12)
        self.humidity_bool_vent.setObjectName("humidity_bool_vent")
        self.gridLayout_21.addWidget(self.humidity_bool_vent, 0, 0, 1, 1)
        self.humidity_bool_restrict_water = QtWidgets.QCheckBox(self.groupBox_12)
        self.humidity_bool_restrict_water.setObjectName("humidity_bool_restrict_water")
        self.gridLayout_21.addWidget(self.humidity_bool_restrict_water, 1, 0, 1, 1)
        self.horizontalLayout_17.addLayout(self.gridLayout_21)
        self.gridLayout_11.addWidget(self.groupBox_12, 2, 1, 1, 1)
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_24.setObjectName("groupBox_24")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.groupBox_24)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.humidity_bool_alert = QtWidgets.QCheckBox(self.groupBox_24)
        self.humidity_bool_alert.setObjectName("humidity_bool_alert")
        self.verticalLayout_14.addWidget(self.humidity_bool_alert)
        self.horizontalLayout_32.addLayout(self.verticalLayout_14)
        self.gridLayout_11.addWidget(self.groupBox_24, 2, 0, 1, 1)
        self.horizontalLayout_14.addLayout(self.gridLayout_11)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.water_bool_alert = QtWidgets.QCheckBox(self.groupBox_17)
        self.water_bool_alert.setObjectName("water_bool_alert")
        self.verticalLayout_8.addWidget(self.water_bool_alert)
        self.horizontalLayout_21.addLayout(self.verticalLayout_8)
        self.gridLayout_14.addWidget(self.groupBox_17, 2, 0, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_16.setObjectName("groupBox_16")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_20 = QtWidgets.QLabel(self.groupBox_16)
        self.label_20.setObjectName("label_20")
        self.gridLayout_18.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_16)
        self.label_21.setObjectName("label_21")
        self.gridLayout_18.addWidget(self.label_21, 1, 0, 1, 1)
        self.water_soil_moisture_min = QtWidgets.QSpinBox(self.groupBox_16)
        self.water_soil_moisture_min.setObjectName("water_soil_moisture_min")
        self.gridLayout_18.addWidget(self.water_soil_moisture_min, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_16)
        self.label_23.setObjectName("label_23")
        self.gridLayout_18.addWidget(self.label_23, 1, 2, 1, 1)
        self.water_soil_moisture_max = QtWidgets.QSpinBox(self.groupBox_16)
        self.water_soil_moisture_max.setObjectName("water_soil_moisture_max")
        self.gridLayout_18.addWidget(self.water_soil_moisture_max, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_16)
        self.label_22.setObjectName("label_22")
        self.gridLayout_18.addWidget(self.label_22, 0, 2, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout_18)
        self.gridLayout_14.addWidget(self.groupBox_16, 0, 1, 1, 1)
        self.groupBox_29 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_29.setObjectName("groupBox_29")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.groupBox_29)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_67 = QtWidgets.QLabel(self.groupBox_29)
        self.label_67.setObjectName("label_67")
        self.gridLayout_30.addWidget(self.label_67, 0, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.groupBox_29)
        self.label_68.setObjectName("label_68")
        self.gridLayout_30.addWidget(self.label_68, 1, 0, 1, 1)
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.groupBox_29)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.gridLayout_30.addWidget(self.lcdNumber_16, 0, 1, 1, 1)
        self.lcdNumber_17 = QtWidgets.QLCDNumber(self.groupBox_29)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.gridLayout_30.addWidget(self.lcdNumber_17, 1, 1, 1, 1)
        self.horizontalLayout_47.addLayout(self.gridLayout_30)
        self.gridLayout_14.addWidget(self.groupBox_29, 2, 2, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_19.setObjectName("groupBox_19")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_40 = QtWidgets.QLabel(self.groupBox_19)
        self.label_40.setObjectName("label_40")
        self.gridLayout_26.addWidget(self.label_40, 2, 0, 1, 1)
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.groupBox_19)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.gridLayout_26.addWidget(self.lcdNumber_10, 1, 1, 1, 1)
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.groupBox_19)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.gridLayout_26.addWidget(self.lcdNumber_12, 3, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_19)
        self.label_39.setObjectName("label_39")
        self.gridLayout_26.addWidget(self.label_39, 1, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_19)
        self.label_41.setObjectName("label_41")
        self.gridLayout_26.addWidget(self.label_41, 3, 0, 1, 1)
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.groupBox_19)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.gridLayout_26.addWidget(self.lcdNumber_11, 2, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_19)
        self.label_38.setObjectName("label_38")
        self.gridLayout_26.addWidget(self.label_38, 0, 0, 1, 1)
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.groupBox_19)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.gridLayout_26.addWidget(self.lcdNumber_9, 0, 1, 1, 1)
        self.horizontalLayout_22.addLayout(self.gridLayout_26)
        self.gridLayout_14.addWidget(self.groupBox_19, 0, 2, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_15.setEnabled(False)
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_24 = QtWidgets.QLabel(self.groupBox_15)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_37.addWidget(self.label_24)
        self.water_time_of_watering = QtWidgets.QTimeEdit(self.groupBox_15)
        self.water_time_of_watering.setObjectName("water_time_of_watering")
        self.horizontalLayout_37.addWidget(self.water_time_of_watering)
        self.gridLayout_22.addLayout(self.horizontalLayout_37, 0, 1, 1, 1)
        self.groupBox_33 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_33.setTitle("")
        self.groupBox_33.setObjectName("groupBox_33")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout(self.groupBox_33)
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.water_bool_period = QtWidgets.QRadioButton(self.groupBox_33)
        self.water_bool_period.setObjectName("water_bool_period")
        self.gridLayout_33.addWidget(self.water_bool_period, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_33)
        self.label_25.setObjectName("label_25")
        self.gridLayout_33.addWidget(self.label_25, 0, 2, 1, 1)
        self.water_bool_amount = QtWidgets.QRadioButton(self.groupBox_33)
        self.water_bool_amount.setObjectName("water_bool_amount")
        self.gridLayout_33.addWidget(self.water_bool_amount, 1, 0, 1, 1)
        self.water_amount = QtWidgets.QSpinBox(self.groupBox_33)
        self.water_amount.setObjectName("water_amount")
        self.gridLayout_33.addWidget(self.water_amount, 1, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox_33)
        self.label_60.setObjectName("label_60")
        self.gridLayout_33.addWidget(self.label_60, 1, 2, 1, 1)
        self.water_time_watering_duration = QtWidgets.QTimeEdit(self.groupBox_33)
        self.water_time_watering_duration.setObjectName("water_time_watering_duration")
        self.gridLayout_33.addWidget(self.water_time_watering_duration, 0, 1, 1, 1)
        self.horizontalLayout_61.addLayout(self.gridLayout_33)
        self.gridLayout_22.addWidget(self.groupBox_33, 1, 1, 1, 1)
        self.horizontalLayout_20.addLayout(self.gridLayout_22)
        self.gridLayout_14.addWidget(self.groupBox_15, 2, 1, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout.setObjectName("verticalLayout")
        self.water_trigers_sensors = QtWidgets.QRadioButton(self.groupBox_14)
        self.water_trigers_sensors.setObjectName("water_trigers_sensors")
        self.verticalLayout.addWidget(self.water_trigers_sensors)
        self.water_trigers_time = QtWidgets.QRadioButton(self.groupBox_14)
        self.water_trigers_time.setObjectName("water_trigers_time")
        self.verticalLayout.addWidget(self.water_trigers_time)
        self.water_trigers_off = QtWidgets.QRadioButton(self.groupBox_14)
        self.water_trigers_off.setChecked(True)
        self.water_trigers_off.setObjectName("water_trigers_off")
        self.verticalLayout.addWidget(self.water_trigers_off)
        self.gridLayout_14.addWidget(self.groupBox_14, 0, 0, 1, 1)
        self.horizontalLayout_19.addLayout(self.gridLayout_14)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.groupBox_18)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.alerts_bool_sms = QtWidgets.QCheckBox(self.groupBox_18)
        self.alerts_bool_sms.setEnabled(False)
        self.alerts_bool_sms.setObjectName("alerts_bool_sms")
        self.gridLayout_17.addWidget(self.alerts_bool_sms, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_18)
        self.label_26.setEnabled(False)
        self.label_26.setObjectName("label_26")
        self.gridLayout_17.addWidget(self.label_26, 0, 1, 1, 1)
        self.alerts_bool_on_screen = QtWidgets.QCheckBox(self.groupBox_18)
        self.alerts_bool_on_screen.setEnabled(False)
        self.alerts_bool_on_screen.setObjectName("alerts_bool_on_screen")
        self.gridLayout_17.addWidget(self.alerts_bool_on_screen, 0, 0, 1, 1)
        self.alerts_text_on_screen = QtWidgets.QLineEdit(self.groupBox_18)
        self.alerts_text_on_screen.setEnabled(False)
        self.alerts_text_on_screen.setText("")
        self.alerts_text_on_screen.setObjectName("alerts_text_on_screen")
        self.gridLayout_17.addWidget(self.alerts_text_on_screen, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_18)
        self.label_29.setEnabled(False)
        self.label_29.setObjectName("label_29")
        self.gridLayout_17.addWidget(self.label_29, 3, 1, 1, 1)
        self.alerts_path_sound = QtWidgets.QLineEdit(self.groupBox_18)
        self.alerts_path_sound.setEnabled(False)
        self.alerts_path_sound.setObjectName("alerts_path_sound")
        self.gridLayout_17.addWidget(self.alerts_path_sound, 1, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_18)
        self.label_27.setEnabled(False)
        self.label_27.setObjectName("label_27")
        self.gridLayout_17.addWidget(self.label_27, 1, 1, 1, 1)
        self.alerts_bool_sound = QtWidgets.QCheckBox(self.groupBox_18)
        self.alerts_bool_sound.setEnabled(False)
        self.alerts_bool_sound.setObjectName("alerts_bool_sound")
        self.gridLayout_17.addWidget(self.alerts_bool_sound, 1, 0, 1, 1)
        self.alerts_bool_email = QtWidgets.QCheckBox(self.groupBox_18)
        self.alerts_bool_email.setEnabled(False)
        self.alerts_bool_email.setObjectName("alerts_bool_email")
        self.gridLayout_17.addWidget(self.alerts_bool_email, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_18)
        self.label_28.setEnabled(False)
        self.label_28.setObjectName("label_28")
        self.gridLayout_17.addWidget(self.label_28, 2, 1, 1, 1)
        self.alerts_sms_number = QtWidgets.QLineEdit(self.groupBox_18)
        self.alerts_sms_number.setEnabled(False)
        self.alerts_sms_number.setObjectName("alerts_sms_number")
        self.gridLayout_17.addWidget(self.alerts_sms_number, 2, 2, 1, 1)
        self.alerts_email_address = QtWidgets.QLineEdit(self.groupBox_18)
        self.alerts_email_address.setEnabled(False)
        self.alerts_email_address.setObjectName("alerts_email_address")
        self.gridLayout_17.addWidget(self.alerts_email_address, 3, 2, 1, 1)
        self.horizontalLayout_25.addLayout(self.gridLayout_17)
        self.gridLayout_16.addWidget(self.groupBox_18, 0, 0, 1, 1)
        self.horizontalLayout_24.addLayout(self.gridLayout_16)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.groupBox_22)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_27.setTitle("")
        self.groupBox_27.setObjectName("groupBox_27")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.groupBox_27)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_46 = QtWidgets.QLabel(self.groupBox_27)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_43.addWidget(self.label_46)
        self.manual_bool_water_on = QtWidgets.QRadioButton(self.groupBox_27)
        self.manual_bool_water_on.setObjectName("manual_bool_water_on")
        self.horizontalLayout_43.addWidget(self.manual_bool_water_on)
        self.manual_bool_water_off = QtWidgets.QRadioButton(self.groupBox_27)
        self.manual_bool_water_off.setChecked(True)
        self.manual_bool_water_off.setObjectName("manual_bool_water_off")
        self.horizontalLayout_43.addWidget(self.manual_bool_water_off)
        self.horizontalLayout_45.addLayout(self.horizontalLayout_43)
        self.gridLayout_29.addWidget(self.groupBox_27, 1, 0, 1, 1)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_26.setTitle("")
        self.groupBox_26.setObjectName("groupBox_26")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.groupBox_26)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_45 = QtWidgets.QLabel(self.groupBox_26)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_40.addWidget(self.label_45)
        self.manual_bool_light_on = QtWidgets.QRadioButton(self.groupBox_26)
        self.manual_bool_light_on.setObjectName("manual_bool_light_on")
        self.horizontalLayout_40.addWidget(self.manual_bool_light_on)
        self.manual_bool_light_off = QtWidgets.QRadioButton(self.groupBox_26)
        self.manual_bool_light_off.setChecked(True)
        self.manual_bool_light_off.setObjectName("manual_bool_light_off")
        self.horizontalLayout_40.addWidget(self.manual_bool_light_off)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41.addWidget(self.groupBox_26)
        self.gridLayout_29.addLayout(self.horizontalLayout_41, 0, 0, 1, 1)
        self.groupBox_28 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_28.setTitle("")
        self.groupBox_28.setObjectName("groupBox_28")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.groupBox_28)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_66 = QtWidgets.QLabel(self.groupBox_28)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_44.addWidget(self.label_66)
        self.manual_bool_vent_on = QtWidgets.QRadioButton(self.groupBox_28)
        self.manual_bool_vent_on.setObjectName("manual_bool_vent_on")
        self.horizontalLayout_44.addWidget(self.manual_bool_vent_on)
        self.manual_bool_vent_off = QtWidgets.QRadioButton(self.groupBox_28)
        self.manual_bool_vent_off.setChecked(True)
        self.manual_bool_vent_off.setObjectName("manual_bool_vent_off")
        self.horizontalLayout_44.addWidget(self.manual_bool_vent_off)
        self.horizontalLayout_46.addLayout(self.horizontalLayout_44)
        self.gridLayout_29.addWidget(self.groupBox_28, 3, 0, 1, 1)
        self.groupBox_32 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_32.setTitle("")
        self.groupBox_32.setObjectName("groupBox_32")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.groupBox_32)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_59 = QtWidgets.QLabel(self.groupBox_32)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_26.addWidget(self.label_59)
        self.manual_bool_heating_on = QtWidgets.QRadioButton(self.groupBox_32)
        self.manual_bool_heating_on.setObjectName("manual_bool_heating_on")
        self.horizontalLayout_26.addWidget(self.manual_bool_heating_on)
        self.manual_bool_heating_off = QtWidgets.QRadioButton(self.groupBox_32)
        self.manual_bool_heating_off.setChecked(True)
        self.manual_bool_heating_off.setObjectName("manual_bool_heating_off")
        self.horizontalLayout_26.addWidget(self.manual_bool_heating_off)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_26)
        self.gridLayout_29.addWidget(self.groupBox_32, 2, 0, 1, 1)
        self.horizontalLayout_39.addLayout(self.gridLayout_29)
        self.gridLayout_28.addWidget(self.groupBox_22, 0, 0, 1, 1)
        self.horizontalLayout_38.addLayout(self.gridLayout_28)
        self.tabWidget_2.addTab(self.tab, "")
        self.gridLayout_20.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_20)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.tab_9)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_3.setEnabled(False)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_19.addWidget(self.spinBox_3, 7, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_9)
        self.label_55.setEnabled(False)
        self.label_55.setObjectName("label_55")
        self.gridLayout_19.addWidget(self.label_55, 3, 2, 1, 1)
        self.spinBox_14 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_14.setEnabled(False)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout_19.addWidget(self.spinBox_14, 1, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_4.setEnabled(False)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_19.addWidget(self.spinBox_4, 7, 3, 1, 1)
        self.spinBox_20 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_20.setEnabled(False)
        self.spinBox_20.setObjectName("spinBox_20")
        self.gridLayout_19.addWidget(self.spinBox_20, 2, 3, 1, 1)
        self.spinBox_15 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_15.setEnabled(False)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridLayout_19.addWidget(self.spinBox_15, 2, 1, 1, 1)
        self.spinBox_25 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_25.setEnabled(False)
        self.spinBox_25.setObjectName("spinBox_25")
        self.gridLayout_19.addWidget(self.spinBox_25, 5, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_9)
        self.label_53.setEnabled(False)
        self.label_53.setObjectName("label_53")
        self.gridLayout_19.addWidget(self.label_53, 1, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_9)
        self.label_50.setObjectName("label_50")
        self.gridLayout_19.addWidget(self.label_50, 3, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.tab_9)
        self.label_64.setEnabled(False)
        self.label_64.setObjectName("label_64")
        self.gridLayout_19.addWidget(self.label_64, 5, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_9)
        self.label_37.setEnabled(False)
        self.label_37.setObjectName("label_37")
        self.gridLayout_19.addWidget(self.label_37, 6, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.tab_9)
        self.label_52.setEnabled(False)
        self.label_52.setObjectName("label_52")
        self.gridLayout_19.addWidget(self.label_52, 0, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox.setEnabled(False)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_19.addWidget(self.spinBox, 6, 1, 1, 1)
        self.spinBox_19 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_19.setEnabled(False)
        self.spinBox_19.setObjectName("spinBox_19")
        self.gridLayout_19.addWidget(self.spinBox_19, 1, 3, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_9)
        self.label_36.setEnabled(False)
        self.label_36.setObjectName("label_36")
        self.gridLayout_19.addWidget(self.label_36, 6, 0, 1, 1)
        self.spinBox_24 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_24.setEnabled(False)
        self.spinBox_24.setObjectName("spinBox_24")
        self.gridLayout_19.addWidget(self.spinBox_24, 5, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab_9)
        self.label_51.setObjectName("label_51")
        self.gridLayout_19.addWidget(self.label_51, 4, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.tab_9)
        self.label_61.setEnabled(False)
        self.label_61.setObjectName("label_61")
        self.gridLayout_19.addWidget(self.label_61, 7, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_9)
        self.label_47.setObjectName("label_47")
        self.gridLayout_19.addWidget(self.label_47, 0, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_9)
        self.label_48.setEnabled(False)
        self.label_48.setObjectName("label_48")
        self.gridLayout_19.addWidget(self.label_48, 1, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_9)
        self.label_42.setEnabled(False)
        self.label_42.setObjectName("label_42")
        self.gridLayout_19.addWidget(self.label_42, 7, 0, 1, 1)
        self.spinBox_18 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_18.setEnabled(False)
        self.spinBox_18.setObjectName("spinBox_18")
        self.gridLayout_19.addWidget(self.spinBox_18, 0, 3, 1, 1)
        self.spinBox_21 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_21.setEnabled(False)
        self.spinBox_21.setObjectName("spinBox_21")
        self.gridLayout_19.addWidget(self.spinBox_21, 3, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.tab_9)
        self.label_54.setEnabled(False)
        self.label_54.setObjectName("label_54")
        self.gridLayout_19.addWidget(self.label_54, 2, 2, 1, 1)
        self.spinBox_16 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_16.setObjectName("spinBox_16")
        self.gridLayout_19.addWidget(self.spinBox_16, 3, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.tab_9)
        self.label_49.setEnabled(False)
        self.label_49.setObjectName("label_49")
        self.gridLayout_19.addWidget(self.label_49, 2, 0, 1, 1)
        self.spinBox_17 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_17.setObjectName("spinBox_17")
        self.gridLayout_19.addWidget(self.spinBox_17, 4, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_9)
        self.label_65.setEnabled(False)
        self.label_65.setObjectName("label_65")
        self.gridLayout_19.addWidget(self.label_65, 5, 2, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout_19.addWidget(self.spinBox_13, 0, 1, 1, 1)
        self.spinBox_22 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_22.setEnabled(False)
        self.spinBox_22.setObjectName("spinBox_22")
        self.gridLayout_19.addWidget(self.spinBox_22, 4, 3, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_9)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_19.addWidget(self.spinBox_2, 6, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_9)
        self.label_56.setEnabled(False)
        self.label_56.setObjectName("label_56")
        self.gridLayout_19.addWidget(self.label_56, 4, 2, 1, 1)
        self.horizontalLayout_23.addLayout(self.gridLayout_19)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.tab_10)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_20.setTitle("")
        self.groupBox_20.setObjectName("groupBox_20")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_62 = QtWidgets.QLabel(self.groupBox_20)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_34.addWidget(self.label_62)
        self.hardware_settings_read_frequency = QtWidgets.QSpinBox(self.groupBox_20)
        self.hardware_settings_read_frequency.setProperty("value", 15)
        self.hardware_settings_read_frequency.setObjectName("hardware_settings_read_frequency")
        self.horizontalLayout_34.addWidget(self.hardware_settings_read_frequency)
        self.label_63 = QtWidgets.QLabel(self.groupBox_20)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_34.addWidget(self.label_63)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_34)
        self.gridLayout_27.addWidget(self.groupBox_20, 0, 0, 1, 1)
        self.horizontalLayout_29.addLayout(self.gridLayout_27)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.verticalLayout_11.addWidget(self.tabWidget_3)
        self.horizontalLayout_28.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_36.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionShow_log_files = QtWidgets.QAction(MainWindow)
        self.actionShow_log_files.setObjectName("actionShow_log_files")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.light_trigers_sensors.toggled['bool'].connect(self.groupBox_38.setEnabled)
        self.light_control_onoff.toggled['bool'].connect(self.groupBox_35.setDisabled)
        self.light_control_pid.toggled['bool'].connect(self.groupBox_35.setEnabled)
        self.light_trigers_off.toggled['bool'].connect(self.groupBox_3.setDisabled)
        self.light_trigers_time.toggled['bool'].connect(self.groupBox_3.setEnabled)
        self.temperature_trigers_off.toggled['bool'].connect(self.groupBox_9.setDisabled)
        self.temperature_trigers_off.toggled['bool'].connect(self.groupBox_6.setDisabled)
        self.temperature_trigers_time.toggled['bool'].connect(self.groupBox_9.setEnabled)
        self.temperature_trigers_time.toggled['bool'].connect(self.groupBox_6.setEnabled)
        self.temperature_trigers_sensors.toggled['bool'].connect(self.groupBox_36.setEnabled)
        self.temperature_control_onoff.toggled['bool'].connect(self.groupBox_34.setDisabled)
        self.temperature_control_pid.toggled['bool'].connect(self.groupBox_34.setEnabled)
        self.light_trigers_off.toggled['bool'].connect(self.groupBox_35.setDisabled)
        self.temperature_trigers_off.toggled['bool'].connect(self.groupBox_34.setDisabled)
        self.light_trigers_off.toggled['bool'].connect(self.groupBox_38.setDisabled)
        self.light_trigers_time.toggled['bool'].connect(self.groupBox_35.setDisabled)
        self.light_trigers_time.toggled['bool'].connect(self.groupBox_38.setDisabled)
        self.light_trigers_sensors.toggled['bool'].connect(self.light_control_onoff.setChecked)
        self.light_trigers_sensors.toggled['bool'].connect(self.groupBox_35.setDisabled)
        self.temperature_trigers_sensors.toggled['bool'].connect(self.temperature_control_onoff.setChecked)
        self.temperature_trigers_time.toggled['bool'].connect(self.groupBox_34.setDisabled)
        self.temperature_trigers_off.toggled['bool'].connect(self.groupBox_36.setDisabled)
        self.temperature_trigers_time.toggled['bool'].connect(self.groupBox_36.setDisabled)
        self.temperature_trigers_sensors.toggled['bool'].connect(self.groupBox_34.setDisabled)
        self.humidity_trigers_sensors.toggled['bool'].connect(self.groupBox_12.setEnabled)
        self.humidity_trigers_off.toggled['bool'].connect(self.groupBox_12.setDisabled)
        self.water_trigers_off.toggled['bool'].connect(self.groupBox_15.setDisabled)
        self.water_trigers_time.toggled['bool'].connect(self.groupBox_15.setEnabled)
        self.water_trigers_sensors.toggled['bool'].connect(self.groupBox_15.setEnabled)
        self.water_trigers_sensors.toggled['bool'].connect(self.groupBox_33.setDisabled)
        self.temperature_trigers_time.toggled['bool'].connect(self.temperature_time_heating_on.setEnabled)
        self.temperature_trigers_time.toggled['bool'].connect(self.temperature_time_heating_off.setEnabled)
        self.temperature_trigers_time.toggled['bool'].connect(self.label_14.setEnabled)
        self.temperature_trigers_time.toggled['bool'].connect(self.label_15.setEnabled)
        self.temperature_trigers_sensors.toggled['bool'].connect(self.groupBox_9.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RPGreenhouse"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.mpl), _translate("MainWindow", "Greenhouse graph"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.mpl1), _translate("MainWindow", "Weather graph"))
        self.label_75.setText(_translate("MainWindow", "Temperature (up - down)"))
        self.label_78.setText(_translate("MainWindow", "Water used (last 24h - 7 days)"))
        self.label_85.setText(_translate("MainWindow", "Soil moisture (average - min - max)"))
        self.label_77.setText(_translate("MainWindow", "Batery level"))
        self.label_74.setText(_translate("MainWindow", "Humidity"))
        self.label_76.setText(_translate("MainWindow", "Light (broadband - visible - infrared)"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_16), _translate("MainWindow", "Current greenhouse data"))
        self.label_69.setText(_translate("MainWindow", "Humidity"))
        self.label_70.setText(_translate("MainWindow", "Temperature (sun - shade)"))
        self.label_71.setText(_translate("MainWindow", "Sunlight (broadband - visible - infrared)"))
        self.label_72.setText(_translate("MainWindow", "Soil moisture"))
        self.label_73.setText(_translate("MainWindow", "Rainfall (24 hours - 7 days)"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_17), _translate("MainWindow", "Current weather data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mpl_tab), _translate("MainWindow", "Data"))
        self.groupBox_38.setTitle(_translate("MainWindow", "Control method"))
        self.light_control_onoff.setText(_translate("MainWindow", "On/Off"))
        self.light_control_pid.setText(_translate("MainWindow", "PID"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Min/max light"))
        self.label_4.setText(_translate("MainWindow", "lm"))
        self.label_2.setText(_translate("MainWindow", "Min"))
        self.label.setText(_translate("MainWindow", "Max"))
        self.label_3.setText(_translate("MainWindow", "lm"))
        self.groupBox_2.setTitle(_translate("MainWindow", "RGB shift"))
        self.label_7.setText(_translate("MainWindow", "Blue"))
        self.label_8.setText(_translate("MainWindow", "Green"))
        self.label_9.setText(_translate("MainWindow", "Red"))
        self.groupBox.setTitle(_translate("MainWindow", "Action on breach"))
        self.light_bool_alert.setText(_translate("MainWindow", "Alert"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Set light by:"))
        self.light_trigers_sensors.setText(_translate("MainWindow", "Sensors"))
        self.light_trigers_time.setText(_translate("MainWindow", "Time"))
        self.light_trigers_off.setText(_translate("MainWindow", "Off"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Current light levels"))
        self.label_31.setText(_translate("MainWindow", "Broadband"))
        self.label_30.setText(_translate("MainWindow", "Visible"))
        self.label_35.setText(_translate("MainWindow", "Infrared"))
        self.groupBox_35.setTitle(_translate("MainWindow", "PID controls"))
        self.label_80.setText(_translate("MainWindow", "Ki"))
        self.label_79.setText(_translate("MainWindow", "Kp"))
        self.label_81.setText(_translate("MainWindow", "Kd"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Time settings"))
        self.label_6.setText(_translate("MainWindow", "Off"))
        self.label_5.setText(_translate("MainWindow", "On"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Light"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Set temperature by:"))
        self.temperature_trigers_sensors.setText(_translate("MainWindow", "Sensors"))
        self.temperature_trigers_time.setText(_translate("MainWindow", "Time"))
        self.temperature_trigers_off.setText(_translate("MainWindow", "Off"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Min/max temperature"))
        self.label_11.setText(_translate("MainWindow", "Min"))
        self.label_10.setText(_translate("MainWindow", "Max"))
        self.label_12.setText(_translate("MainWindow", "C"))
        self.label_13.setText(_translate("MainWindow", "C"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Heating time"))
        self.label_14.setText(_translate("MainWindow", "On"))
        self.label_15.setText(_translate("MainWindow", "Off"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Action on breach"))
        self.temperature_bool_temp_alert.setText(_translate("MainWindow", "Alert"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Venting time"))
        self.label_58.setText(_translate("MainWindow", "Off"))
        self.label_57.setText(_translate("MainWindow", "On"))
        self.groupBox_25.setTitle(_translate("MainWindow", "Current temp"))
        self.label_44.setText(_translate("MainWindow", "Today min"))
        self.label_32.setText(_translate("MainWindow", "Up"))
        self.label_43.setText(_translate("MainWindow", "Today max"))
        self.label_33.setText(_translate("MainWindow", "Down"))
        self.groupBox_34.setTitle(_translate("MainWindow", "PID controls"))
        self.label_82.setText(_translate("MainWindow", "Kp"))
        self.label_83.setText(_translate("MainWindow", "Ki"))
        self.label_84.setText(_translate("MainWindow", "Kd"))
        self.groupBox_36.setTitle(_translate("MainWindow", "Control method"))
        self.temperature_control_onoff.setText(_translate("MainWindow", "On/Off"))
        self.temperature_control_pid.setText(_translate("MainWindow", "PID"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Temperature"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Min/max humidity"))
        self.label_18.setText(_translate("MainWindow", "%"))
        self.label_19.setText(_translate("MainWindow", "%"))
        self.label_16.setText(_translate("MainWindow", "Max"))
        self.label_17.setText(_translate("MainWindow", "Min"))
        self.groupBox_23.setTitle(_translate("MainWindow", "Current humidity"))
        self.groupBox_37.setTitle(_translate("MainWindow", "Last 24h extremes"))
        self.label_88.setText(_translate("MainWindow", "Maximum"))
        self.label_89.setText(_translate("MainWindow", "Minimum"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Set humidity by:"))
        self.humidity_trigers_sensors.setText(_translate("MainWindow", "Sensors"))
        self.humidity_trigers_off.setText(_translate("MainWindow", "Off"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Regulate by:"))
        self.humidity_bool_vent.setText(_translate("MainWindow", "Vent"))
        self.humidity_bool_restrict_water.setText(_translate("MainWindow", "Restrict or turn on watering"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Action on breach"))
        self.humidity_bool_alert.setText(_translate("MainWindow", "Alert"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Humidity"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Action on breach"))
        self.water_bool_alert.setText(_translate("MainWindow", "Alert"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Min/max soil moisture"))
        self.label_20.setText(_translate("MainWindow", "Max"))
        self.label_21.setText(_translate("MainWindow", "Min"))
        self.label_23.setText(_translate("MainWindow", "%"))
        self.label_22.setText(_translate("MainWindow", "%"))
        self.groupBox_29.setTitle(_translate("MainWindow", "Water used"))
        self.label_67.setText(_translate("MainWindow", "Last 24h"))
        self.label_68.setText(_translate("MainWindow", "Last week"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Current soil moisture"))
        self.label_40.setText(_translate("MainWindow", "Sensor 3"))
        self.label_39.setText(_translate("MainWindow", "Sensor 2"))
        self.label_41.setText(_translate("MainWindow", "Sensor 4"))
        self.label_38.setText(_translate("MainWindow", "Sensor 1"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Watering time and amount"))
        self.label_24.setText(_translate("MainWindow", "Turn on water at"))
        self.water_bool_period.setText(_translate("MainWindow", "For"))
        self.label_25.setText(_translate("MainWindow", "sec"))
        self.water_bool_amount.setText(_translate("MainWindow", "Pour"))
        self.label_60.setText(_translate("MainWindow", "litres"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Watering by:"))
        self.water_trigers_sensors.setText(_translate("MainWindow", "Sensors"))
        self.water_trigers_time.setText(_translate("MainWindow", "Time"))
        self.water_trigers_off.setText(_translate("MainWindow", "Off"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Watering"))
        self.alerts_bool_sms.setText(_translate("MainWindow", "SMS"))
        self.label_26.setText(_translate("MainWindow", "Text"))
        self.alerts_bool_on_screen.setText(_translate("MainWindow", "On screen alert"))
        self.label_29.setText(_translate("MainWindow", "Email address"))
        self.label_27.setText(_translate("MainWindow", "Sound file"))
        self.alerts_bool_sound.setText(_translate("MainWindow", "Sound"))
        self.alerts_bool_email.setText(_translate("MainWindow", "Email"))
        self.label_28.setText(_translate("MainWindow", "Mobile number"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Alerts"))
        self.label_46.setText(_translate("MainWindow", "Watering"))
        self.manual_bool_water_on.setText(_translate("MainWindow", "On"))
        self.manual_bool_water_off.setText(_translate("MainWindow", "Off"))
        self.label_45.setText(_translate("MainWindow", "Light"))
        self.manual_bool_light_on.setText(_translate("MainWindow", "On"))
        self.manual_bool_light_off.setText(_translate("MainWindow", "Off"))
        self.label_66.setText(_translate("MainWindow", "Vent"))
        self.manual_bool_vent_on.setText(_translate("MainWindow", "On"))
        self.manual_bool_vent_off.setText(_translate("MainWindow", "Off"))
        self.label_59.setText(_translate("MainWindow", "Heating"))
        self.manual_bool_heating_on.setText(_translate("MainWindow", "On"))
        self.manual_bool_heating_off.setText(_translate("MainWindow", "Off"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Manual"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
        self.label_55.setText(_translate("MainWindow", "Soil moisture 4"))
        self.label_53.setText(_translate("MainWindow", "Soil moisture 2"))
        self.label_50.setText(_translate("MainWindow", "Temperature (1wire)"))
        self.label_64.setText(_translate("MainWindow", "DHT outside"))
        self.label_37.setText(_translate("MainWindow", "Heating control"))
        self.label_52.setText(_translate("MainWindow", "Soil moisture 1"))
        self.label_36.setText(_translate("MainWindow", "Rain gauge"))
        self.label_51.setText(_translate("MainWindow", "DHT inside"))
        self.label_61.setText(_translate("MainWindow", "TextLabel"))
        self.label_47.setText(_translate("MainWindow", "tsl2561 indoors"))
        self.label_48.setText(_translate("MainWindow", "tsl2561 outdoors"))
        self.label_42.setText(_translate("MainWindow", "Soil moisture outside"))
        self.label_54.setText(_translate("MainWindow", "Soil moisture 3"))
        self.label_49.setText(_translate("MainWindow", "tsl2561 spare"))
        self.label_65.setText(_translate("MainWindow", "Vent/fan control"))
        self.label_56.setText(_translate("MainWindow", "Light control"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "GPIO"))
        self.label_62.setText(_translate("MainWindow", "Sensor read/log frequency"))
        self.label_63.setText(_translate("MainWindow", "sec"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Various"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Hardware"))
        self.actionShow_log_files.setText(_translate("MainWindow", "Show log files"))
        self.actionClose.setText(_translate("MainWindow", "Close"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

